# The MUP Project Pathway

## Pathway Description

The MUP Project pathway is designed to expose students to planning practice through the independent application of knowledge to a planning problem. MUP projects require a client - typically a planning or related agency who is commissioning your work on a planning problem or report. While the MUP project is guided in part by the needs of the client, it should be completed largely independently by the MUP student. MUP projects may be initiated by one student, but can also be completed by teams of MUP students if the scope of work is appropriate for a team.

You will complete 8 credit hours of UP 598: Master's Project during your second year in which you carry out your project. Your project will be guided in part by the needs of your client and in part by a planning faculty member. As part of the capstone adoption process, both your client and the faculty member will sign off on your project proposal. The faculty member will sign off on your completed project.

## Expected Outputs

The primary output from the MUP project is a completed plan, report, or other form of professional output that demonstrates the application of planning skills and knowledge to a relevant question or problem. The audience for the MUP project is typically planning practitioners or planning stakeholders. A strong project typically includes not only a major written output but also involves some form of independent engagement with a planning problem which might include community outreach and engagement, data collection and analysis, facilitating public meetings, and developing interim and final outputs designed to be consumed by multiple public and professional audiences.

## Adopting This Pathway

In the spring of your MUP 1 year, you will be asked to declare your capstone pathway (workshop, project, or thesis). At this point, your choice is not binding. You will also receive detailed descriptions of the four UP 510: Plan Making Workshop sections being offered during your second year. You will select a proposed pathway, and then indicate your rank order preference for all four of the UP 510: Plan Making Workshop sections.

After all MUP 1 students have declared a preliminary capstone pathway, students declaring the project pathway will be assigned to one UP 510: Plan Making Workshop section for the second year and will be authorized to register only for that assigned workshop section. 

## Resources

Completed MUP Projects are archived in the [UIUC IDEALS system](https://www.ideals.illinois.edu/collections/1318). A list of recent MUP projects can be [found here](https://web.faa.illinois.edu/app/uploads/sites/2/2024/09/MUP-Capstone-List-2019-to-present.pdf).

## Completing This Pathway

The Department requires the completion of a total of 8 credit hours of UP 598: Master's Project with a passing grade to satisfy this capstone pathway. UP 598 credit hours are registered under the unique CRN of your project faculty advisor and your advisor will ultimately assess your progress and assign an appropriate grade for these credit hours at the end of each semester. In most cases, students pursuing this pathway will take 4 credit hours of UP 598 in the fall semester of their second year and the remaining 4 credit hours of UP 598 in the spring semester of their second year. 
## Project Process Guidelines

### Project Proposal Development

The starting place for a MUP project is proposal development. A typical MUP project proposal is 6-8 pages long, and outlines the following:

1.  Outlines the background, rationale for the project and identifies the project's client (1-2 pages).

2.  Describes the scope of work for the project based upon specific actions, events, and outputs (2 pages).

3.  Describes the final output of the project (1-2 pages)

4.  Provides details on project timeline (1-2 pages).

### Project Proposal Approval

Project proposals should typically be developed between your second and third semesters in the MUP program. At the beginning of the fall semester of your second year, you will formally adopt your capstone. For students pursuing the MUP Project, adoption includes review and approval of your project proposal by your client, by a departmental faculty member who agrees to advise your project, and by the Director of Graduate Studies.

During the approval process, your client, project faculty advisor, and the DGS may request revisions or alterations to your project proposal before signing off on it. You must submit a completed and signed capstone adoption form with your final project proposal attached to the DGS before the Graduate College's official 10th day of classes deadline in the fall semester of your second year in the program. If you have not successfully completed adoption of the project pathway by this time, you will be asked to switch to a different capstone pathway.

### Initiating An Approved Project

After your project proposal is approved and you have formally adopted the project pathway, it's time to get to work on your project!  There are two early process steps that can often make or break your project timeline:

- **IRB Approval:** If your project involves primary data collection like surveys, interviews, or focus groups, you may need to submit an [IRB Protocol](https://oprs.research.illinois.edu/submissions/submitting-irb) before these forms of primary data collection can begin. IRB applications require a lot of details and may require several rounds of review and revision on the part of the IRB. Students may fill out an IRB application but the application must be submitted by a faculty member, typically your committee chair, serving in the role of Principal Investigator for your research protocol.

Budget at 4-6 weeks from your initial submission for the review and approval of human subjects research by the IRB.

**Data Acquisition:** Both primary data and secondary data can take time to collect or acquire. It is important to initiate data collection or acquisition early in the project process. Students often underestimate the time it will take to acquire, clean, and prepare both primary and secondary data for use in their project. You should request feedback on any data acquisition activities from your project faculty advisor and from your client as you prepare and finalize your project timeline.

### Project Completion

MUP students on the project pathway will typically complete their project in the second half of their final semester in the MUP program. To complete the project, the student will submit to their project faculty advisor a complete and polished final project manuscript along with the MUP Capstone Exit Form. While this manuscript should be a complete version of the professional product that will be submitted to the client, and it's best practice to have the client review prior to submission for faculty approval, this final product does not have to be formally adopted by the client prior to review and approval for satisfying the MUP project requirement.

1. Final capstone project reviewed by the client; client signs capstone exit form.

2. Final capstone project reviewed by the capstone faculty advisor; faculty advisor signs capstone exit form.

3. Final capstone project reviewed bby the Director of Graduate Studies; DGS signs capstone exit form.

4. Passing grade on UP 598: Master's Project submitted by the capstone faculty advisor to certify completion of the MUP project.

## Client / Faculty Advisor Expectations

1. Both the project client and project faculty advisor will read and provide feedback on the project proposal prior to formal adoption of the project.

2. The Project Faculty Advisor will play an active role in guiding the development and execution of the MUP project. In order to do they, the Faculty Advisor should a) have expertise and familiarity with the topic and approach; b) be willing to commit to work with the student closely throughout the project's execution; and, c) be willing to coordinate with the student and client to support the successful execution and completion of the MUP project.

3. The Project Faculty Advisor should  meet regularly with the student while they are registered for project credit hours.

4. The student is expected to provide updates on their progress to their faculty advisor and client at least once per month. At least one full meeting with the faculty advisor and client both in attendance is expected each semester after the project is adopted.

6. It is the responsibility of the student to be aware of and accountable for all deadlines and timing associated with project completion. 

7. Any concerns from the Faculty Advisor or the Client should be communicated to the Director of Graduate Studies to provide additional support for students in the project execution process.