# The MUP Workshop Pathway

## Pathway Description

The MUP Workshop pathway is designed to expose students to planning practice through applying skills and knowledge to multiple planning problems. You will complete at least two 4-credit hour UP 510: Plan Making Workshop classes in which you gain this exposure and experience working in partnership with planning practitioners or community groups and working under the guidance of an experienced planning faculty member. The audience for the outputs from workshops are typically typically planning practitioners or planning stakeholders. 

## Expected Outputs

Workshops tend to have outputs that feed into existing practice contexts - plans, reports, guidelines, etc. This can vary widely depending upon the needs of the community partner that the workshop is engaging with.

Your workshop experience will likely include some facilitation of both expert and public input to help inform your outputs. The goal of workshops is twofold - to build your knowledge and experience of planning *through practice*, and to create beneficial guidance and support for the institutions and communities that your workshop engages with.

We expect that by the completion of the workshop pathway that you have:

1. Contributed to the production of one or multiple professional-quality outputs that are designed to be adopted and implemented by the community partner.

2. Taken on multiple clear roles within your workshop projects that result in individual work products which you can claim ownership of that demonstrate your professional skills.

3. Gained substantive experience with professional planning practice as a workshop team that helps to inform your own personal vision and approach to planning practice.

## Adopting This Pathway

In the spring of your MUP 1 year, you will be asked to declare your capstone pathway (workshop, project, or thesis). At this point, your choice is not binding. You will also receive detailed descriptions of the four UP 510: Plan Making Workshop sections being offered during your second year. You will select a proposed pathway, and then indicate your rank order preference for all four of the UP 510: Plan Making Workshop sections.

After all MUP 1 students have declared a preliminary capstone pathway, students declaring the workshop pathway will be assigned to two UP 510: Plan Making Workshop sections for the second year (one in the fall and one in the spring) and will be authorized to register only for those assigned workshop sections. 

## Completing This Pathway

The Department requires the completion of a total of 8 credit hours of UP 510: Plan Making Workshop to satisfy this capstone pathway. You must receive a passing grade for all 8 credit hours taken.