---
title: "Introduction to FAA Career Services"
format: html
toc: true
editor: source
---
## Session Overview

### Learn

We will be joined by Ana Rodas from the FAA Career Center who will talk about career development resources and strategies.

## Before we Meet

Think about questions you have regarding professional development that you'd like to ask staff from our Career Center.

## After we Meet

### Professional Network Mapping and Strategy

Map out your key professional contacts and connections. It may be useful to make a list of those professional contacts who you consider to be a resource to you. Think about how to organize these contacts and how to strategies around areas for further network development.

### Review Current Job Listings

Review 3-5 active job ads for positions that you may be interested in (it is likely too early to start applying, but worth starting to track positions that are out there). Think about stated (and unstated) qualifications that are part of these ads. How can you build exposure over the next two semesters that will help you qualify for these positions?

## Additional Resources
