---
title: "Portfolio Development"
format: html
toc: true
editor: source
---
## Session Overview

One of your graduation requirements is to develop a professional portfolio. We will use UP 591 as a venue to develop and workshop how you will present yourself and your vision for **professional practice**. Your draft portfolio is due in December, so this condensed workshop covers both the structure of a strong portfolio and peer review of your draft outline and key documents.

### Learn

We will begin our class by reviewing the overall structure of a portfolio and its broader goals. This will draw upon the portfolio description in the MUP handbook as well as the [portfolio milestone description](../milestones/04_portfolio.qmd) which is part of this class.

### Reflect

We will think about key documents and forms of evidence that you will incorporate in your portfolio. These may include examples that come from your coursework, internships, capstone, and other forms of engagement you have undertaken that help define and provide evidence for your identity as a planning professional.

### Review

Time to share your draft portfolio outlines and key documents with each other and provide peer feedback.

## Before we Meet

- Review the [portfolio requirements](../milestones/04_portfolio.qmd) outlined in the Portfolio Milestone description.

- Watch our **November pre-session video** (portfolio as evidence of competence).

- Identify 2-3 key documents which you may want to include or in some way highlight in your portfolio. Bring digital copies of those documents to class.

- Bring a draft outline of your portfolio, organized in a logical fashion, so you can receive feedback from a peer.

- Bring a digital copy of your updated Plan of Study document. You may want to review your updated narrative statements about your professional identity before we meet.

- If you haven't yet, initiate your mid-fall mentor check-in.

## After we Meet

- Refine your portfolio toward the December draft (constituent pieces and statements organized in a logical fashion).

- Accomplish your November goal.

**Course milestone:** Draft Portfolio (Dec) in progress.

**Mentoring milestone:** Mid-fall mentee-initiated check-in.

## Additional Resources