---
title: "Workshop and Capstone Pathway Adoption"
format: html
toc: true
sidebar: true
editor: source
---

## Deliverable Overview

In the spring semester before your second year, you will identify which capstone pathway you plan to pursue and will share your preferences for which workshop courses you will take in your second year. The process of adopting your capstone is described below, including the use of the capstone adoption [web form](https://forms.illinois.edu/sec/1915761140) (for all pathways) and the [capstone adoption form](files/02_CapstoneAdoption.pdf) (required in addition to the web form for all pathways).

## Capstone Pathways

There are three pathways to satisfy the practice component of the MUP capstone requirement. By default, you are expected to pursue the Plan Making Workshop pathway. Students wishing to pursue the Project Pathway or Thesis Pathway need to describe their projects in detail and petition to adopt an alternate pathway.

**Plan Making Workshop:** Exposure to professional planning practice by completing two plan making workshops. The audience for the projects completed in these workshops is typically planning and policy practitioners and decision makers. Faculty workshop leaders work in partnership with an institution, organization, or community partner to determine the scope and deliverables from the workshop in advance. Typical workshop deliverables may be a report, a plan, or other professional quality work.

**Master's Project:** A professional project or analysis focusing on a topic relevant to the student's selected concentration and career goals. The audience for a master’s project is typically planning and policy practitioners and decisionmakers. The capstone deliverable may be a report, a plan, or other professional quality work. The project is conducted for or with an external client.

**Masters Thesis:** A scholarly applied or basic research work conducted under the formal Thesis Guidelines of the Department and Graduate College. The audience for a master’s thesis is typically academic and applied researchers. The thesis option is most appropriate for MUP students with a strong interest in pursuing a research-oriented career or PhD degree.

## Pathway Documentation

One of your first tasks is to "adopt" your capstone project. You will do this in the spring before your second year by completing the [following form](https://forms.illinois.edu/sec/1915761140) to indicate your capstone pathway and preferences regarding workshop offerings.

### UP 510 Workshop Descriptions

You will have four UP 510 Plan Making Workshop courses to choose from in your second year of the program. Most MUP students will elect to take two workshops, one in the fall semester, and one in the spring semester. Given the intensive nature of workshops, the department does not allow students to register for more than one UP 510 offering per semester.

Unlike most of the other classes you take in our department, we will assign you to workshop courses taking into account your stated preferences as well as the unique demands of each workshop offering. You will complete the capstone adoption [web form](https://forms.illinois.edu/sec/1915761140) to share your preferences. The department will then assign and enroll you in fall and spring workshop offerings.

Below, are general descriptions of the UP 510: Plan Making Workshops being offered in Academic Year 2025-2026.

#### Retrofitting Suburbia Using Small Area Plans (Fall 2025)

**Instructor:** [Dustin Allred](https://urban.illinois.edu/people/profiles/dustin-allred-aicp/)

**Semester Offered:** Fall 2025

**Workshop External Partner:** City of Bloomington, IL

**Workshop Description:** Like many cities in the US, the central Illinois city of Bloomington is interested in seeing the site of a dying mall rehabilitated through redevelopment. The 54 acre Eastland Mall is a strategically important site east of downtown Bloomington that presents an interesting opportunity to apply planning ideas like “retrofitting suburbia” in the creation of a small area plan that describes how this site can evolve into a more sustainable, just, healthy, and community-serving place. Although the city has some ideas for what could happen on this site, it would be up to the students in the workshop to engage with key stakeholders and collect and analyze data on existing conditions to create a compelling and feasible vision for how the site could be transformed.

**Expected Outputs:** Outputs from this workshop will include a polished professional small area type plan that synthesizes stakeholder input and background information and includes a development concept, site plan and implementation strategies. Students will also be expected to present this information to decision makers at the City of Bloomington.

#### Climate and Workforce Development (Fall 2025)

**Instructor:** [Emily Guske](https://ler.illinois.edu/directory/emily-guske/)

**Semester Offered:** Fall 2025

**Workshop External Partner:** Illinois Climate Jobs Institute

**Workshop Description:** This workshop is a collaboration with the Climate Jobs Institute (CJI) in the School of Labor and Employment Relations. Established to provide research support the goals of the Climate and Equitable Jobs Act, CJI is evaluating the impact of the political coalition who won support for the Act on the current development of climate-friendly (“green”) jobs. The process of making green jobs available and viable is complicated. It requires place-based networks of unions, community colleges, employers, not-for-profits and other key actors in the community and economic development process. Students in the workshop will investigate the Climate and Equitable Jobs Act’s transition from idea to reality, by evaluating the place-based networks of actors (unions, community colleges, employers, community organizations) attempting to make training programs for green jobs a reality. We will begin with background reading on green jobs and the alliances between unions and environmental organizations. The class will then assemble evidence on the effectiveness of green jobs programs elsewhere. Finally, students will use basic research methods for collecting secondary data and conducting interviews to provide an assessment of the status of green jobs programs across four Illinois cities. The results will aid CJI in supporting the development of the job-training networks whose effective operation is necessary for the law to reach its goals.

**Expected Outputs:** At the workshop’s conclusion, you will produce a detailed, comparative study of climate-jobs political coalitions across key Illinois cities. The study will apply the political theories you learned to data on organizations active in climate jobs, and interviews to determine the current challenges facing the law’s implementation. You will conclude the course with experience evaluating how plans and policies are actually implemented.

#### Global Urban Economic Development (Spring 2026)

**Instructor:** [Kerry Fang](https://urban.illinois.edu/people/profiles/kerry-fang/)

**Semester Offered:** Spring 2026

**Workshop External Partner:** Politecnico di Milano (Italy)

**Workshop Description:** This workshop is a two-campus collaboration between UIUC with Politecnico di Milano in Milan (Italy). It embraces urban economic development in a global setting, with a special focus on industrial clusters, urban creativity and innovation, and entrepreneurship. It offers a first-hand international planning experience in partnership with your Italian peers. In this workshop, we will learn theories, analytical methods, and development practices in a seminar- and discussion-based fashion from instructors and students from both campuses, introducing a wide range of global development approaches from first-hand experiences. More importantly, in this project-based class, we will team up with cross-continental peers to work on comparative projects, to explore effective ways of urban economic development, apply comprehensive methods to track the performance of different regions, and formulate policy recommendations to improve local development, create jobs, boost innovation, and prompt entrepreneurship.

**Expected Outputs:** At the end of this workshop, you will produce an international comparative study in partnership with your peers from Politecnico di Milano. In this study, you will apply economic development theories and analysis tools to solve concrete planning problems in both domestic and international settings. You will also be able to formulate evidence-based policy recommendations and adapt them to different political settings.

#### Central Illinois Housing Needs Assessment (Spring 2026)

**Instructor:** [Andrew Greenlee](https://urban.illinois.edu/people/profiles/andrew-greenlee/)

**Semester Offered:** Spring 2026

**Workshop External Partner:** Illinois Housing Lab

**Workshop Description:** Central Illinois’ housing landscape is rapidly changing due to major changes in population as well as major changes in both state and federal housing policy. Many communities throughout the region lack the capacity to strategically understand local housing needs or to think systematically about how local needs fit into the broader regional housing landscape. To engage these issues, in this workshop we will conduct a regional housing needs assessment with the goal of both describing the evolving housing landscape present throughout central Illinois and then providing guidance on potential strategies to address identified needs.

Over the course of this workshop, we will work with the Central Illinois Land Bank Authority and other housing agencies in central Illinois to analyze trends related to housing supply and demand, and to develop a broader understanding of institutional needs and goals related to housing. Students in this workshop will work with public and proprietary sources of housing and community demographic information to produce a regional picture of housing needs, and will also gain experience conducting interviews and facilitating conversations with local communities and institutions about housing and community change.

**Expected Outputs:** Outputs from this workshop will include a polished professional report summarizing the process and findings from the needs assessment. As part of this needs assessment, secondary outputs will include a data dashboard for sharing information with local communities as well as an intervention toolkit that describes potential intervention strategies to address needs that are identified.

### Additional Documentation for Projects and Theses

-   For the **Project Pathway** you need to share a detailed description of your projects subject and scope, a description of your client, and need to secure the signature of your client and the faculty member who has agreed to supervise your project. Detailed [project proposal guidelines](../guidelines/project.qmd) are available under the pathway description.

-   For the **Thesis Pathway** you need to share a project abstract and need to secure the signature of your thesis advisor and a second faculty committee member. You should have also shared a detailed proposal with both your thesis adviser and your other committee member by the time you adopt your capstone.Detailed [thesis proposal guidelines](../guidelines/thesis.qmd) are available under the pathway description.

## Milestone Deliverable

If you pursue the Workshop pathway, the only needed documentation is the submission of the pathway adoption web form in the spring of your first year, and the capstone adoption form in the fall of the second year. For those who are petitioning to adopt the project or thesis pathway, please complete the [Capstone Adoption Form](files/02_CapstoneAdoption.pdf), including all required signatures (based upon the capstone pathway you are pursuing) and including your proposal and submit to the file dropbox below.

## Resources

-   [Capstone Adoption Form](files/02_CapstoneAdoption.pdf)
- Detailed [pathway descriptions](../guidelines/guidelines.qmd) and proposal guidelines for the [Project](../guidelines/project.qmd) and [Thesis](../guidelines/thesis.qmd) pathways

## Submission Instructions

All capstone pathways will complete the capstone adoption [web form](https://forms.illinois.edu/sec/1915761140) to indicate the proposed capstone pathway and preferences regarding workshop offerings.

Individuals pursuing the **workshop** pathway must subsequently submit the PDF Capstone Adoption Form (no additional signatures required). The initial submission should be made using the below file dropbox:

Individuals pursuing the **project** or **thesis** pathways must subsequently submit the PDF Capstone Adoption Form with all required signatures to petition into these alternate pathways. The initial submission should be made using the below file dropbox:

<iframe src="https://uofi.app.box.com/f/5affe018728548b485e246d2d755e0b4" height="900" width="800">

</iframe>
